// lines are accepted if 1st char is '#', or 2nd char is '=', or 7th char is '='
// and cause an error report if they do not match one of the formats.
// all other lines are ignored.

[origin chars - max 47]
// note that # and x are reserved for the local station,
// otherwise, if not included in this list, 
// @ is for unknown, P for stns starting PW, and V for those starting AVX.
+=UKDUN2
*=AVX949
v=AVX913
n=NAVITER
N=NAVITER2
b=Bkpark
g=UKGRL2
G=UKGRL3
D=EGDD
c=EGTC
d=EGLD
t=EGBT
w=WOG2
h=husbos
W=Watford
S=SafeSky
B=UKBIG
O=OxfBarton
e=Enstone
a=AA959
F=FLYMASTER
A=AA957
C=Chesham
k=MiltnKy
k=PWMiltnKy
K=MiltonKey
o=oxford
m=muchbirch
H=BGCHinton

[defines]
#define AFH 575		// airfield height in feet amsl
#define APH 800		// approach height amsl
#define MBP 4		// minutes before passive status
#define MBE 10		// minutes before expired status
#define DST 16		// distant status(km)

// this is the actual station we want to specify as local for Win32
[local station info]
stnlat=51.880667
stnlon=-0.564500
stnrad=20.0
stnnam=Totternho
// this is the aprs login name for win32
w32nam=Dunst2

[colours]
// standard text colours:
// 31=red, 32=green, 33=yellow, 34=blue, 35=magenta, 36=cyan, 37=white, 39=default
// (38;5;nm are 256 colour pallet values, probably they should all use this)
defcol=39;0m		// default
actcol=38;5;14m		// cyan:	active <3 mins (MBP)
lowcol=32m		// green:	active below 800ft (APH) taxying
stacol=32;4m		// green_ul:	used for displaying sort type
pascol=38;5;226m	// yellow:	passive 4 (MBP) to 10 (MBE) minutes
expcol=38;5;244m	// black:	expired >10 mins (MBE) greyed out
stlcol=35m		// magenta:	active stealth
notcol=31;1m		// red:		active notrack
discol=34;1m		// blue:	distant 
pasdis=38;5;223m	// lght yellow:	passive distant
